### ISSUE TITLE
Object navigation (config A)

### ISSUE THREAD

**Issue by XinyuSun** [gunagg/zson#2]
Hi! Thanks for releasing the code.

I tried to train an imagenav model using the script (imagenav-v1-hm3d-ovrl-rn50.sh) in the codebase, but I failed to re-implement the success rate (20.1% vs. 31.3% reported in the paper) when transferred to objectnav. I am wondering if you can provide the training log of config A if convenient. Thanks a lot!

**Comment by XinyuSun** [comment]
We have reproduced the objectnav result by 32.7% using the intermediate checkpoint (462.5M), thanks a lot!

**Comment by leyuan-sun** [comment]
@XinyuSun  I met the problem in the last step.` batch: error: s_p_parse_file: unable to status file /etc/slurm-llnl/slurm.conf`
Do I need to build slurm?

**Comment by DocLuci** [comment]
@XinyuSun hi 
I'm also a student in SCUT.  We are tring to dreproduced the objectnav recently,  but we have encountered limitations in terms of computing power . Noticing that you've reproduced this project successfully ,  so maybe you could share the pretrained models with us so that we could reproduced the project , and I will appreciate it very much .  please feel free contact me by 562961809@qq.com
